package com.fl.dashboard.enums;

public enum NotificationType {
    TAREFA_ATRIBUIDA,
    TAREFA_STATUS_ALTERADO,
    TAREFA_PRAZO_PROXIMO,
    TAREFA_CONCLUIDA,
    TAREFA_EDITADA,
    TAREFA_REMOVIDA,
    NOTIFICACAO_GERAL,
    PROJETO_ATRIBUIDO,
    PROJETO_STATUS_ALTERADO,
    PROJETO_EDITADO,
    PROJETO_ATUALIZADO,
    PROJETO_PRAZO_ALTERADO,
    PROJETO_PRAZO_PROXIMO,
    PROJETO_CONCLUIDO,
    PROJETO_REMOVIDO,
    PROPOSTA_ATUALIZADA,
    SUBTAREFA_ATRIBUIDA,
    SUBTAREFA_CONCLUIDA,
    TAREFA_RECORRENTE_CRIADA
}
