package com.fl.dashboard.enums;

public enum NotificationType {
    TAREFA_ATRIBUIDA,
    TAREFA_STATUS_ALTERADO,
    TAREFA_PRAZO_PROXIMO,
    TAREFA_CONCLUIDA,
    NOTIFICACAO_GERAL,
    PROJETO_ATRIBUIDO,
    PROJETO_ATUALIZADO,
    PROJETO_CONCLUIDO
}
