name: fl-dashboard
services:
  - name: fl-dashboard-backend
    dockerfile_path: backend/Dockerfile
    source_dir: backend
    git:
      branch: main
      repo_clone_url: https://github.com/carlosLapa/fl-dashboard.git
    health_check:
      http_path: /actuator/health
