version: '3.8'

services:
  frontend:
    image: endovelic/fldashboard-frontend:prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://sea-lion-app-hnrzs.ondigitalocean.app
    depends_on:
      - backend

  backend:
    image: endovelic/fldashboard-backend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://fldashboard-db-cluster-do-user-18750969-0.l.db.ondigitalocean.com:25060/defaultdb?sslMode=REQUIRED
      - SPRING_DATASOURCE_USERNAME=doadmin
      - SPRING_DATASOURCE_PASSWORD=${DO_DATABASE_PASSWORD}