name: fl-dashboard
services:
  - name: backend
    source_dir: ./backend
    dockerfile_path: ./backend/Dockerfile
    git:
      branch: main
      repo_clone_url: https://github.com/carlosLapa/fl-dashboard.git
