name: Database Migration Check

on:
  push:
    branches: [main]
    paths:
      - 'backend/src/main/resources/db/migration/**'
      - '.github/workflows/flyway-check.yml'
  pull_request:
    branches: [main]
    paths:
      - 'backend/src/main/resources/db/migration/**'

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          timeout 60s bash -c 'until mysql -h127.0.0.1 -uroot -prootpassword -e "SELECT 1"; do sleep 2; done'
          echo "MySQL is ready!"
          
      - name: Validate migrations
        run: |
          cd backend
          mvn flyway:validate -Dflyway.url=jdbc:mysql://localhost:3306/testdb -Dflyway.user=root -Dflyway.password=rootpassword
          
      - name: Apply migrations
        run: |
          cd backend
          mvn flyway:migrate -Dflyway.url=jdbc:mysql://localhost:3306/testdb -Dflyway.user=root -Dflyway.password=rootpassword
          
      - name: Verify migrations
        run: |
          cd backend
          mvn flyway:info -Dflyway.url=jdbc:mysql://localhost:3306/testdb -Dflyway.user=root -Dflyway.password=rootpassword
