name: Database Migration Check

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/src/main/resources/db/migration/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/src/main/resources/db/migration/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: fldashboard_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Validate Flyway Migrations Syntax
      run: |
        cd backend
        mvn flyway:validate -Dflyway.url=jdbc:mysql://localhost:3306/fldashboard_test -Dflyway.user=root -Dflyway.password=root
    
    - name: Show Migration Info (Test DB)
      run: |
        cd backend
        mvn flyway:info -Dflyway.url=jdbc:mysql://localhost:3306/fldashboard_test -Dflyway.user=root -Dflyway.password=root
    
    - name: Show Migration Info (Production)
      if: github.ref == 'refs/heads/main'
      run: |
        cd backend
        mvn flyway:info -Dflyway.url=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslMode=REQUIRED -Dflyway.user=${{ secrets.DB_USERNAME }} -Dflyway.password=${{ secrets.DB_PASSWORD }}
      
    - name: Generate Migration Report
      if: github.event_name == 'pull_request'
      run: |
        cd backend
        echo "## Database Migration Changes" > migration_report.md
        echo "The following migrations will be applied:" >> migration_report.md
        echo '```' >> migration_report.md
        mvn flyway:info -Dflyway.url=jdbc:mysql://localhost:3306/fldashboard_test -Dflyway.user=root -Dflyway.password=root | grep -A 100 "Pending Migrations" >> migration_report.md
        echo '```' >> migration_report.md
        echo "Please review these changes carefully before merging." >> migration_report.md
        
    - name: Comment PR with Migration Info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const migrationReport = fs.readFileSync('backend/migration_report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: migrationReport
          });