name: Build and Deploy Frontend

on:
  push:
    branches: [main]
    paths:
      - 'frontweb/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: frontweb
          push: true
          tags: |
            endovelic/fldashboard-frontend:latest
            endovelic/fldashboard-frontend:${{ github.sha }}
          build-args: |
            REACT_APP_API_URL=https://fl-backend-app-6v3xd.ondigitalocean.app