name: Pre-Deployment Database Check

on:
  workflow_dispatch:  # Manual trigger only
  
jobs:
  check-production-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Check Production Migration Status
      run: |
        cd backend
        mvn flyway:info -Dflyway.url=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslMode=REQUIRED -Dflyway.user=${{ secrets.DB_USERNAME }} -Dflyway.password=${{ secrets.DB_PASSWORD }}
      
    - name: Generate Production Migration Report
      run: |
        cd backend
        echo "## Production Database Migration Status" > prod_migration_report.md
        echo "The following migrations would be applied to production:" >> prod_migration_report.md
        echo '```' >> prod_migration_report.md
        mvn flyway:info -Dflyway.url=jdbc:mysql://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}?sslMode=REQUIRED -Dflyway.user=${{ secrets.DB_USERNAME }} -Dflyway.password=${{ secrets.DB_PASSWORD }} | grep -A 100 "Pending Migrations" >> prod_migration_report.md
        echo '```' >> prod_migration_report.md
        echo "**IMPORTANT:** Review these changes carefully. Migrations will be applied automatically when the application is deployed." >> prod_migration_report.md
        cat prod_migration_report.md